<a href="https://colab.research.google.com/github/jogeuncheol/2022_BoostCamp_AI_Pre-Course/blob/main/matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.array([
  [1, -2, 3],
  [7, 5, 0],
  [-2, -1, 2]
])

Y = np.array([
  [0, 1],
  [1, -1],
  [-2, 1]
])
# numpy에선 @연산을 사용함
X @ Y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [4]:
Z = np.array([
  [3, 2, 1],
  [0, 1, 0],
  [-2, 0, 1]
])
np.inner(X, Z)

array([[  2,  -2,   1],
       [ 31,   5, -14],
       [ -6,  -1,   6]])

In [6]:
# X multiplication np.transpose(Z)
X @ Z.T

array([[  2,  -2,   1],
       [ 31,   5, -14],
       [ -6,  -1,   6]])